# Site settings
title: Retail Link Blog
email: enquiries@retaillinkrecruitment.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Why shop around when Retail Link has everything in store? Find out how we can offer you the best retail recruitment service at: 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.retaillinkrecruitment.co.uk/blog"
tel: "07790 735809"

# Build settings
markdown: kramdown